name: CICD
on:
  push:
    paths-ignore:
      - LICENSE
      - images
      - terraform
      - azure-pipeline.yml
      
      
env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
  CLUSTER_ID: ${{ secrets.CLUSTER_ID }}
  REPO_DIRECTORY: ${{ secrets.REPO_DIRECTORY}}

permissions:
  checks: write
jobs:
  OnPush:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
      
    - name: Install libraries
      run: |
        pip install --upgrade pip nutter
    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0

        
    - name: Run Tests
      run: |
        nutter run "$REPO_DIRECTORY/unit-tests/" --cluster_id $CLUSTER_ID --recursive --junit_report --timeout 500
    
    - name: Update databricks repo
      if: success() 
      run: |
        databricks repos update --path $REPO_DIRECTORY --branch "${{github.ref_name}}"  
        
